#!/usr/bin/env bash
set -eux
# mamba create \
#   -y \
#   --file conda-linux-64.lock \
#   --prefix ${NB_PYTHON_PREFIX}
# mamba clean -yaf # clean up downloaded files and indexes

export MKL_INTERFACE_LAYER=LP64

/srv/conda/bin/activate notebook  # Activate the conda environment before pip installing

# git clone https://github.com/WorldCereal/presto-worldcereal.git
# cd presto-worldcereal
# pip install --no-dependencies .
# cd ..

git clone https://github.com/WorldCereal/worldcereal-classification.git
cd worldcereal-classification
pip install --no-dependencies .
cd ..

conda deactivate

jupyter server extension enable --py nbgitpuller --sys-prefix