#!/usr/bin/env bash
set -eux
mamba create \
  -y \
  --file conda-linux-64.lock \
  --prefix ${NB_PYTHON_PREFIX}
mamba clean -yaf # clean up downloaded files and indexes

git clone https://github.com/WorldCereal/presto-worldcereal.git
cd presto-worldcereal
pip install --no-dependencies .
cd ..

git clone https://github.com/WorldCereal/worldcereal-classification.git
cd worldcereal-classification
pip install --no-dependencies .
cd ..

jupyter server extension enable --py nbgitpuller --sys-prefix